# Generated by Django 5.2.8 on 2025-11-24 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('given_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('profile_description', models.TextField(null=True)),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('required_caregiving_type', models.CharField(blank=True, max_length=50, null=True)),
                ('other_requirements', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('caregiver_user', models.OneToOneField(db_column='caregiver_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='caregiver_photos/')),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('caregiving_type', models.CharField(blank=True, max_length=50, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'db_table': 'caregiver',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_user', models.OneToOneField(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('house_rules', models.TextField(blank=True, null=True)),
                ('dependent_description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_recipient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_time_slots', models.CharField(blank=True, max_length=255, null=True)),
                ('service_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('job', models.OneToOneField(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.job')),
            ],
            options={
                'db_table': 'job_detail',
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_applied', models.DateField(blank=True, null=True)),
                ('job', models.ForeignKey(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('caregiver', models.ForeignKey(db_column='caregiver_user_id', on_delete=django.db.models.deletion.CASCADE, to='core.caregiver')),
            ],
            options={
                'db_table': 'job_application',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('member', models.OneToOneField(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.member')),
                ('house_number', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='member',
            field=models.ForeignKey(blank=True, db_column='member_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.member'),
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('allow_caregiver_initiate', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('caregiver', models.ForeignKey(db_column='caregiver_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='core.caregiver')),
                ('member', models.ForeignKey(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='core.member')),
            ],
            options={
                'db_table': 'contact_request',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('work_hours', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('caregiver', models.ForeignKey(blank=True, db_column='caregiver_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.caregiver')),
                ('member', models.ForeignKey(blank=True, db_column='member_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.member')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
