# Generated by Django 5.2.8 on 2025-11-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('allow_caregiver_initiate', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('caregiver', models.ForeignKey(db_column='caregiver_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='core.caregiver')),
                ('member', models.ForeignKey(db_column='member_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='core.member')),
            ],
            options={
                'db_table': 'contact_request',
            },
        ),
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_recipient_age', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_time_slots', models.CharField(blank=True, max_length=255, null=True)),
                ('service_frequency', models.CharField(blank=True, max_length=100, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('job', models.OneToOneField(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.job')),
            ],
            options={
                'db_table': 'job_detail',
            },
        ),
    ]
