# Generated by Django 5.2.8 on 2025-11-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Fix job_detail: remove id column and make job_id the primary key
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    -- Drop id column if it exists
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='job_detail' AND column_name='id'
                    ) THEN
                        ALTER TABLE job_detail DROP CONSTRAINT IF EXISTS job_detail_pkey;
                        ALTER TABLE job_detail DROP COLUMN id;
                        ALTER TABLE job_detail ADD PRIMARY KEY (job_id);
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Fix contact_request: add contact_request_id if needed
        migrations.RunSQL(
            sql="""
                DO $$ 
                BEGIN
                    -- Add contact_request_id if it doesn't exist
                    IF NOT EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='contact_request' AND column_name='contact_request_id'
                    ) THEN
                        CREATE SEQUENCE IF NOT EXISTS contact_request_contact_request_id_seq;
                        ALTER TABLE contact_request 
                        ADD COLUMN contact_request_id INTEGER DEFAULT nextval('contact_request_contact_request_id_seq');
                        UPDATE contact_request 
                        SET contact_request_id = nextval('contact_request_contact_request_id_seq')
                        WHERE contact_request_id IS NULL;
                        ALTER TABLE contact_request ALTER COLUMN contact_request_id SET NOT NULL;
                    END IF;
                    -- Make it primary key
                    ALTER TABLE contact_request DROP CONSTRAINT IF EXISTS contact_request_pkey;
                    ALTER TABLE contact_request ADD PRIMARY KEY (contact_request_id);
                    -- Remove id column if it exists
                    IF EXISTS (
                        SELECT 1 FROM information_schema.columns 
                        WHERE table_name='contact_request' AND column_name='id'
                    ) THEN
                        ALTER TABLE contact_request DROP COLUMN id;
                    END IF;
                END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Update Django's model state to match database
        migrations.RemoveField(
            model_name='contactrequest',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jobdetail',
            name='id',
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='contact_request_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='job',
            field=models.OneToOneField(db_column='job_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='detail', serialize=False, to='core.job'),
        ),
    ]
