# Generated by Django 5.2.8 on 2025-11-24 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_address_options_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='caregiver',
            field=models.ForeignKey(blank=True, db_column='caregiver_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.caregiver'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='member',
            field=models.ForeignKey(blank=True, db_column='member_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.member'),
        ),
        migrations.AddField(
            model_name='job',
            name='member',
            field=models.ForeignKey(blank=True, db_column='member_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.member'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='caregiver',
            field=models.ForeignKey(db_column='caregiver_user_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='core.caregiver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(db_column='job_id', default=2, on_delete=django.db.models.deletion.CASCADE, to='core.job'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='caregiver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='caregiver_photos/'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
